repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: python -m unittest discover
        language: system
        types: [python]
        pass_filenames: false
