"""add new distributions

Revision ID: 087169116d12
Revises: 1dc24294c698
Create Date: 2025-07-26 18:41:33.144005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087169116d12'
down_revision = '1dc24294c698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_distribution', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.drop_column('energy_distribution')

    # ### end Alembic commands ###
