"""add world tick to sim stats

Revision ID: 0b7037b06339
Revises: 00f9182e3675
Create Date: 2025-09-11 08:50:46.751331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7037b06339'
down_revision = '00f9182e3675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world_tick', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_simulation_stats_world_tick'), ['world_tick'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_stats_world_tick'))
        batch_op.drop_column('world_tick')

    # ### end Alembic commands ###
