"""add ai state

Revision ID: 1cff94243be4
Revises: 087169116d12
Create Date: 2025-07-29 00:45:00.769023

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1cff94243be4"
down_revision = "087169116d12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("critter", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ai_state",
                sa.Enum("IDLE", "RESTING", name="aistate"),
                nullable=False,
                server_default="IDLE",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("critter", schema=None) as batch_op:
        batch_op.drop_column("ai_state")

    # ### end Alembic commands ###
