"""add new distributions

Revision ID: 1dc24294c698
Revises: 7a07cc4e5bc0
Create Date: 2025-07-26 18:11:32.769499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc24294c698'
down_revision = '7a07cc4e5bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hunger_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('thirst_distribution', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.drop_column('thirst_distribution')
        batch_op.drop_column('hunger_distribution')
        batch_op.drop_column('health_distribution')

    # ### end Alembic commands ###
