"""fix name of column

Revision ID: 20d91ff22367
Revises: 5f86c1e5a11f
Create Date: 2025-08-31 03:02:48.118936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d91ff22367'
down_revision = '5f86c1e5a11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_concordance_herbivore', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_concordance_carnivore', sa.Float(), nullable=True))
        batch_op.drop_column('herbivore_concordance')
        batch_op.drop_column('carnivore_concordance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carnivore_concordance', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_concordance', sa.FLOAT(), nullable=True))
        batch_op.drop_column('avg_concordance_carnivore')
        batch_op.drop_column('avg_concordance_herbivore')

    # ### end Alembic commands ###
