"""add diet

Revision ID: 22a487b347a9
Revises: fe78595e3022
Create Date: 2025-08-27 17:51:14.511973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a487b347a9'
down_revision = 'fe78595e3022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet', sa.Enum('HERBIVORE', 'CARNIVORE', name='diettype'), server_default='herbivore', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.drop_column('diet')

    # ### end Alembic commands ###
