"""rename cause of death

Revision ID: 30aa3a69c309
Revises: 1cff94243be4
Create Date: 2025-07-29 09:41:40.272963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aa3a69c309'
down_revision = '1cff94243be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause', sa.Enum('STARVATION', 'THIRST', 'OLD_AGE', 'PREDATION', 'EXHAUSTION', name='causeofdeath'), nullable=True))
        batch_op.drop_column('cause_of_death')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause_of_death', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('cause')

    # ### end Alembic commands ###
