"""add goal distribution

Revision ID: 36838e7ae9af
Revises: bbf6863f416f
Create Date: 2025-08-01 00:08:00.472147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36838e7ae9af'
down_revision = 'bbf6863f416f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_distribution', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.drop_column('goal_distribution')

    # ### end Alembic commands ###
