"""add tile state

Revision ID: 45dbaaca5d9b
Revises: fa39972a9741
Create Date: 2025-07-21 07:45:51.656230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dbaaca5d9b'
down_revision = 'fa39972a9741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tile_state',
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('food_available', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('x', 'y')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile_state')
    # ### end Alembic commands ###
