"""add velocity

Revision ID: 4be17ab6d3f2
Revises: 30aa3a69c309
Create Date: 2025-07-29 19:54:28.137504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be17ab6d3f2'
down_revision = '30aa3a69c309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vx', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vy', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.drop_column('vy')
        batch_op.drop_column('vx')

    # ### end Alembic commands ###
