"""add concordance

Revision ID: 5f86c1e5a11f
Revises: 9f9ad5c6994d
Create Date: 2025-08-31 02:42:25.157924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f86c1e5a11f'
down_revision = '9f9ad5c6994d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('herbivore_concordance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_concordance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_stats', schema=None) as batch_op:
        batch_op.drop_column('carnivore_concordance')
        batch_op.drop_column('herbivore_concordance')

    # ### end Alembic commands ###
