"""Add breeding cooldown

Revision ID: 7a07cc4e5bc0
Revises: 82786d117154
Create Date: 2025-07-26 16:31:11.586479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a07cc4e5bc0'
down_revision = '82786d117154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breeding_cooldown', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.drop_column('breeding_cooldown')

    # ### end Alembic commands ###
