"""add commitment

Revision ID: 7a1f628952f3
Revises: 94cb138dda40
Create Date: 2025-08-08 08:53:36.308414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1f628952f3'
down_revision = '94cb138dda40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commitment', sa.Float(), server_default='1.75', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.drop_column('commitment')

    # ### end Alembic commands ###
