"""more ai states

Revision ID: 7b2ccd943ec9
Revises: 4be17ab6d3f2
Create Date: 2025-07-29 22:58:53.991353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2ccd943ec9'
down_revision = '4be17ab6d3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.alter_column('ai_state',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('IDLE', 'FLEEING', 'RESTING', 'SEEKING_FOOD', 'EATING', 'SEEKING_WATER', 'DRINKING', 'SEEKING_MATE', 'BREEDING', name='aistate'),
               existing_nullable=False,
               existing_server_default=sa.text("'IDLE'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.alter_column('ai_state',
               existing_type=sa.Enum('IDLE', 'FLEEING', 'RESTING', 'SEEKING_FOOD', 'EATING', 'SEEKING_WATER', 'DRINKING', 'SEEKING_MATE', 'BREEDING', name='aistate'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'IDLE'"))

    # ### end Alembic commands ###
