"""add stats

Revision ID: 82786d117154
Revises: f34fde34ff7d
Create Date: 2025-07-26 16:08:42.696332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82786d117154'
down_revision = 'f34fde34ff7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_stats',
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('herbivore_population', sa.Integer(), nullable=True),
    sa.Column('carnivore_population', sa.Integer(), nullable=True),
    sa.Column('age_distribution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tick')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_stats')
    # ### end Alembic commands ###
