"""add metabolism

Revision ID: 8df5ea2fec84
Revises: 36838e7ae9af
Create Date: 2025-08-01 18:07:55.794722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df5ea2fec84'
down_revision = '36838e7ae9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metabolism', sa.Float(), server_default='1.0', nullable=False))
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('size',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('metabolism')

    # ### end Alembic commands ###
