"""add diet

Revision ID: 92d5671db776
Revises: 45dbaaca5d9b
Create Date: 2025-07-26 11:34:17.846739

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92d5671db776"
down_revision = "45dbaaca5d9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("critter", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "diet",
                sa.Enum("HERBIVORE", "CARNIVORE", name="diettype"),
                nullable=False,
                server_default="herbivore",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("critter", schema=None) as batch_op:
        batch_op.drop_column("diet")

    # ### end Alembic commands ###
