"""added event

Revision ID: 94cb138dda40
Revises: efcbf9757290
Create Date: 2025-08-06 07:11:34.616100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cb138dda40'
down_revision = 'efcbf9757290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critter_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('critter_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('event', sa.Enum('BIRTH', 'DEATH', 'BREED', 'ATTACK_SURVIVED', 'ATTACK_KILLED', name='event'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('critter_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_critter_event_critter_id'), ['critter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_critter_event_critter_id'))

    op.drop_table('critter_event')
    # ### end Alembic commands ###
