"""add TrainingStats table

Revision ID: 9f9ad5c6994d
Revises: 22a487b347a9
Create Date: 2025-08-30 23:41:27.508976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9ad5c6994d'
down_revision = '22a487b347a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_stats',
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('herbivore_epsilon', sa.Float(), nullable=True),
    sa.Column('carnivore_epsilon', sa.Float(), nullable=True),
    sa.Column('avg_reward_herbivore', sa.Float(), nullable=True),
    sa.Column('avg_reward_carnivore', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('tick')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_stats')
    # ### end Alembic commands ###
