"""separate distributions by species

Revision ID: a1a5e7c5931e
Revises: 8df5ea2fec84
Create Date: 2025-08-01 18:45:01.220083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a5e7c5931e'
down_revision = '8df5ea2fec84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('herbivore_age_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_age_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_health_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_health_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_hunger_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_hunger_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_thirst_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_thirst_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_energy_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_energy_distribution', sa.Text(), nullable=True))
        batch_op.drop_column('health_distribution')
        batch_op.drop_column('thirst_distribution')
        batch_op.drop_column('hunger_distribution')
        batch_op.drop_column('age_distribution')
        batch_op.drop_column('energy_distribution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_distribution', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('age_distribution', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('hunger_distribution', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('thirst_distribution', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('health_distribution', sa.TEXT(), nullable=True))
        batch_op.drop_column('carnivore_energy_distribution')
        batch_op.drop_column('herbivore_energy_distribution')
        batch_op.drop_column('carnivore_thirst_distribution')
        batch_op.drop_column('herbivore_thirst_distribution')
        batch_op.drop_column('carnivore_hunger_distribution')
        batch_op.drop_column('herbivore_hunger_distribution')
        batch_op.drop_column('carnivore_health_distribution')
        batch_op.drop_column('herbivore_health_distribution')
        batch_op.drop_column('carnivore_age_distribution')
        batch_op.drop_column('herbivore_age_distribution')

    # ### end Alembic commands ###
