"""add parents to dead critter

Revision ID: b0e69ad167cf
Revises: 92d5671db776
Create Date: 2025-07-26 15:52:29.307082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e69ad167cf'
down_revision = '92d5671db776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_one_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_two_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.drop_column('parent_two_id')
        batch_op.drop_column('parent_one_id')

    # ### end Alembic commands ###
