"""add last action

Revision ID: bbf6863f416f
Revises: ed9957bce9e9
Create Date: 2025-07-30 22:35:23.130908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf6863f416f'
down_revision = 'ed9957bce9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_action', sa.Enum('REST', 'DRINK', 'EAT', 'ATTACK', 'BREED', 'MOVE', 'IDLE', name='actiontype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.drop_column('last_action')

    # ### end Alembic commands ###
