"""add perception

Revision ID: bce1125770ff
Revises: 7a1f628952f3
Create Date: 2025-08-09 14:00:43.907084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce1125770ff'
down_revision = '7a1f628952f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perception', sa.Float(), server_default='8.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.drop_column('perception')

    # ### end Alembic commands ###
