"""add movement progress

Revision ID: ed9957bce9e9
Revises: 7b2ccd943ec9
Create Date: 2025-07-30 01:11:20.619261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9957bce9e9'
down_revision = '7b2ccd943ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movement_progress', sa.Float(), server_default='0.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.drop_column('movement_progress')

    # ### end Alembic commands ###
