"""added lifespan

Revision ID: efcbf9757290
Revises: a1a5e7c5931e
Create Date: 2025-08-04 18:35:54.703225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcbf9757290'
down_revision = 'a1a5e7c5931e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lifespan', sa.Integer(), server_default='2000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critter', schema=None) as batch_op:
        batch_op.drop_column('lifespan')

    # ### end Alembic commands ###
