"""rename fields

Revision ID: f34fde34ff7d
Revises: b0e69ad167cf
Create Date: 2025-07-26 15:56:09.966880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34fde34ff7d'
down_revision = 'b0e69ad167cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dead_critter_original_critter_id'))
        batch_op.create_index(batch_op.f('ix_dead_critter_original_id'), ['original_id'], unique=True)
        batch_op.drop_column('original_critter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_critter_id', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dead_critter_original_id'))
        batch_op.create_index(batch_op.f('ix_dead_critter_original_critter_id'), ['original_critter_id'], unique=1)
        batch_op.drop_column('original_id')

    # ### end Alembic commands ###
