"""Initial migration

Revision ID: fa39972a9741
Revises: 
Create Date: 2025-07-21 07:09:20.366417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa39972a9741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_username'), ['username'], unique=True)

    op.create_table('critter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('hunger', sa.Float(), nullable=True),
    sa.Column('thirst', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('parent_one_id', sa.Integer(), nullable=False),
    sa.Column('parent_two_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_one_id'], ['critter.id'], ),
    sa.ForeignKeyConstraint(['parent_two_id'], ['critter.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dead_critter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_critter_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('cause_of_death', sa.Enum('STARVATION', 'THIRST', 'OLD_AGE', 'PREDATION', name='causeofdeath'), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('time_of_death', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_critter_original_critter_id'), ['original_critter_id'], unique=True)

    op.create_table('dead_critter_children_association',
    sa.Column('dead_critter_id', sa.Integer(), nullable=False),
    sa.Column('child_critter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_critter_id'], ['critter.id'], ),
    sa.ForeignKeyConstraint(['dead_critter_id'], ['dead_critter.id'], ),
    sa.PrimaryKeyConstraint('dead_critter_id', 'child_critter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dead_critter_children_association')
    with op.batch_alter_table('dead_critter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_critter_original_critter_id'))

    op.drop_table('dead_critter')
    op.drop_table('critter')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_username'))

    op.drop_table('player')
    # ### end Alembic commands ###
