"""add medians and quartiles

Revision ID: fe78595e3022
Revises: bce1125770ff
Create Date: 2025-08-09 14:11:43.597276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe78595e3022'
down_revision = 'bce1125770ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('herbivore_speed_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_speed_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_speed_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_speed_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_speed_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_speed_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_size_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_size_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_size_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_size_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_size_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_size_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_metabolism_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_metabolism_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_metabolism_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_metabolism_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_metabolism_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_metabolism_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_perception_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_perception_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_perception_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_perception_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_perception_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_perception_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_commitment_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_commitment_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('herbivore_commitment_q3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_commitment_q1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_commitment_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carnivore_commitment_q3', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_stats', schema=None) as batch_op:
        batch_op.drop_column('carnivore_commitment_q3')
        batch_op.drop_column('carnivore_commitment_median')
        batch_op.drop_column('carnivore_commitment_q1')
        batch_op.drop_column('herbivore_commitment_q3')
        batch_op.drop_column('herbivore_commitment_median')
        batch_op.drop_column('herbivore_commitment_q1')
        batch_op.drop_column('carnivore_perception_q3')
        batch_op.drop_column('carnivore_perception_median')
        batch_op.drop_column('carnivore_perception_q1')
        batch_op.drop_column('herbivore_perception_q3')
        batch_op.drop_column('herbivore_perception_median')
        batch_op.drop_column('herbivore_perception_q1')
        batch_op.drop_column('carnivore_metabolism_q3')
        batch_op.drop_column('carnivore_metabolism_median')
        batch_op.drop_column('carnivore_metabolism_q1')
        batch_op.drop_column('herbivore_metabolism_q3')
        batch_op.drop_column('herbivore_metabolism_median')
        batch_op.drop_column('herbivore_metabolism_q1')
        batch_op.drop_column('carnivore_size_q3')
        batch_op.drop_column('carnivore_size_median')
        batch_op.drop_column('carnivore_size_q1')
        batch_op.drop_column('herbivore_size_q3')
        batch_op.drop_column('herbivore_size_median')
        batch_op.drop_column('herbivore_size_q1')
        batch_op.drop_column('carnivore_speed_q3')
        batch_op.drop_column('carnivore_speed_median')
        batch_op.drop_column('carnivore_speed_q1')
        batch_op.drop_column('herbivore_speed_q3')
        batch_op.drop_column('herbivore_speed_median')
        batch_op.drop_column('herbivore_speed_q1')

    # ### end Alembic commands ###
